### ISSUE TITLE
Avro error with imports in 0.10.1

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/sbt-avrohugger#17]
Hi, I'm importing AVSC schemas in my AVDL files. This is working fine in 0.9.x, but since 0.10.x, I'm getting the following error:

`(modelJVM/avro:generateSpecific) org.apache.avro.SchemaParseException: Can't redefine: com.example.ImportedType`

~~~
at org.apache.avro.Schema$Parser.parse(Schema.java:932)
	at avrohugger.input.parsers.FileInputParser.getSchemaOrProtocols(FileInputParser.scala:53)
	at avrohugger.input.parsers.FileInputParser$$anonfun$3.apply(FileInputParser.scala:67)
	at avrohugger.input.parsers.FileInputParser$$anonfun$3.apply(FileInputParser.scala:66)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
~~~

**Comment by julianpeeters** [comment]
Thanks for the heads up, Marius. I expect to have a fix in the next few days.

P.S. What are you're thoughts on the major change in 0.10.0? (i.e. having avdls and avprs generate a Scala ADT named after the protocol when there are multiple types defined and no message defintions)? Is that going to be noise for you? Would you prefer the ability to turn it on/off in the sbt-plugin?

**Comment by julianpeeters** [comment]
Fixed in version 0.11.0

**Comment by mariussoutier** [comment]
Thanks, looking good!

**Comment by julianpeeters** [comment]
Fantastic. And as always, the confirmation is appreciatied 💯
